name: vendor_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+2
  image_picker: ^0.6.7+12
  fluttertoast: ^7.1.1
  provider: ^4.3.2+2
  cloud_firestore: ^0.14.1+3
  firebase_database: ^4.1.1
  firebase_storage: ^4.0.1
  cloud_firestore_web: ^0.2.1
  firebase_core: ^0.5.0
  firebase_auth:
  firebase_auth_web:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/


